# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [201]:
NICKNAME = "agentWSS"

#### 1. Import the numpy package under the name `np` (★☆☆)

In [202]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
null_vector = np.zeros(10)

print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [7]:
a = np.array([1, 2, 3, 4, 5])

memory_size = a.nbytes

print(memory_size)

40


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [11]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
null_vector = np.zeros(10)

null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [14]:
vector[:] = vector[::-1]

print(vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
matrix = np.arange(9)

matrix = matrix.reshape((3, 3))

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [16]:
array = np.array([1, 2, 0, 0, 4, 0])

indices = np.nonzero(array)

print(indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [17]:
identity_matrix = np.identity(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [20]:
array = np.random.randint(0, 10, size=(3, 3, 3))

print(array)

[[[9 7 3]
  [6 6 7]
  [8 2 5]]

 [[1 8 3]
  [3 7 8]
  [9 3 2]]

 [[0 2 7]
  [6 4 3]
  [3 9 9]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [24]:
array = np.random.rand(10, 10)
print(array)

min_value = array.min()
max_value = array.max()

print(min_value)
print(max_value)

[[0.86683047 0.44244393 0.92707203 0.57735861 0.83267727 0.61010268
  0.0134506  0.73905208 0.94961014 0.68192885]
 [0.60817945 0.76440878 0.78154341 0.62787461 0.83704375 0.10484604
  0.25600251 0.82007021 0.48721442 0.60940043]
 [0.7717571  0.49978847 0.24077767 0.79439605 0.01656411 0.74843517
  0.17561011 0.70008931 0.33329351 0.72322222]
 [0.94563256 0.28149235 0.11942092 0.11142048 0.98234226 0.54518962
  0.44700538 0.93681051 0.03046271 0.20589788]
 [0.60129737 0.8832249  0.86348005 0.3571324  0.9609236  0.48881182
  0.78111181 0.76070858 0.83865397 0.63069417]
 [0.18910035 0.9900914  0.48494159 0.9286148  0.79164068 0.97478666
  0.38176442 0.18016929 0.69084862 0.15840666]
 [0.64480085 0.45197747 0.27415733 0.10887146 0.27625887 0.8218492
  0.86176448 0.68131321 0.55885309 0.26900189]
 [0.28465088 0.5929733  0.88092911 0.36620986 0.57019048 0.96603771
  0.27368474 0.59180518 0.35454562 0.65907412]
 [0.75471899 0.44637534 0.85884537 0.20434136 0.79910277 0.18727222
  0.72994576 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [26]:
vector = np.random.rand(30)
print(vector)

mean_value = vector.mean()

print(mean_value)

[0.42248064 0.57911789 0.6892348  0.98891181 0.61125977 0.40868675
 0.27532624 0.5515008  0.07193849 0.95111466 0.16360424 0.35687155
 0.93562358 0.49663164 0.14147058 0.75277668 0.61603148 0.36068073
 0.57576269 0.77038796 0.76827208 0.44690255 0.21726587 0.91864074
 0.12401833 0.22143119 0.30518674 0.25455422 0.535954   0.35681303]
0.4956150575462583


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [27]:
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0

print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [28]:
array = np.array([[1, 2, 3], [4, 5, 6]])

padded_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)

print(padded_array)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [30]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


nan (не число) — это специальное значение с плавающей запятой, представляющее неопределенное или непредставимое значение. Оно не равно никакому другому значению, в том числе самому себе, и любая операция, включающая nan, приведет к nan.

Значение inf (бесконечность) представляет собой положительную или отрицательную бесконечность, в зависимости от знака. Оно больше любого другого конечного значения, но не больше, чем nan.

Функция set создает объект set, представляющий собой неупорядоченный набор уникальных элементов. Оператор in можно использовать для проверки того, находится ли элемент в наборе. В этом случае np.nan находится в наборе [np.nan].

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [29]:
matrix = np.diag([1, 2, 3, 4], k=-1)

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [31]:
pattern = np.array([[0, 1], [1, 0]])
matrix = np.tile(pattern, (4, 4)).reshape((8, 8))

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th 

---

element? (★☆☆)

In [32]:
index = np.unravel_index(100, (6, 7, 8))

print(index)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [33]:
matrix = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [34]:
matrix = np.random.rand(5, 5)

mean = matrix.mean()
std = matrix.std()
normalized_matrix = (matrix - mean) / std

print(normalized_matrix)

[[-1.46416207 -0.99048159 -0.92393405 -0.35164139  0.55380501]
 [ 0.65102797 -0.9398556   1.21656697 -0.77177166  0.36923079]
 [-0.19115359  0.67456857 -0.33766272  1.50483578 -0.99123334]
 [-1.52539708 -0.15845165  1.50747506  0.76669163  0.15035342]
 [-1.79357801  0.87934177  1.42813104 -0.5486755   1.28597026]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [38]:
color_dtype = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])

print(color_dtype)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [47]:
matrix_a = np.random.rand(5, 3)

matrix_b = np.random.rand(3, 2)

matrix_c = np.dot(matrix_a, matrix_b)

print(matrix_c)

[[1.35750176 0.88508745]
 [1.44455894 0.86951653]
 [0.97832923 0.70815507]
 [0.67497409 0.49847293]
 [0.81316253 0.45737366]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [48]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array[np.where((array > 3) & (array < 8))] = np.negative(array[np.where((array > 3) & (array < 8))])

print(array)

[ 1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [49]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [50]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-50-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-50-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [52]:
array = np.array([-1.5, -0.5, 0.5, 1.5])

rounded_array_ceil = np.ceil(array) 
rounded_array_floor = np.floor(array) 

print(rounded_array_ceil)
print(rounded_array_floor)

[-1. -0.  1.  2.]
[-2. -1.  0.  1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [58]:
array_a = np.random.randint(1, 10, size=(5,))
array_b = np.random.randint(1, 10, size=(5,))

common_values = np.intersect1d(array_a, array_b)

print(common_values)

[1 5 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [57]:
defaults = np.seterr(all = 'ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [59]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [60]:
today = np.datetime64('today')

yesterday = today - np.timedelta64(1, 'D')

tomorrow = today + np.timedelta64(1, 'D')

print(yesterday)  
print(today)  
print(tomorrow) 

2022-12-22
2022-12-23
2022-12-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [61]:
start_date = np.datetime64('2016-07-01')

end_date = np.datetime64('2016-07-31')

dates = np.arange(start_date, end_date+1, dtype='datetime64[D]')

print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [71]:
A = np.ones(5) * 1 
B = np.ones(5) * 2

np.add(A, B, out=A)
np.negative(A, out=A)
np.divide(A, 2, out=A)

print(A)

[-1.5 -1.5 -1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [68]:
array = np.random.rand(5)
integer_part = np.floor(array)
print(integer_part)

array = np.random.rand(5)
integer_part = array.astype(int)
print(integer_part)

array = np.random.rand(5)
integer_part = np.trunc(array)
print(integer_part)

array = np.random.rand(5)
integer_part = np.round(array).astype(int)
print(integer_part)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[0. 0. 0. 0. 0.]
[0 1 0 1 0]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [75]:
a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [77]:
def generator_function():
    for i in range(10):
        yield i
array = np.fromiter(generator_function(), dtype=int)

print(array)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [78]:
vector = np.linspace(0, 1, 10, endpoint=False)

print(vector)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [84]:
array = np.random.random(10)

print(np.sort(array))

[0.01124676 0.06071943 0.1384384  0.1651925  0.20169384 0.24400137
 0.53761742 0.56016771 0.71073842 0.93229251]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [87]:
array = np.arange(5)

print(np.add.reduce(array))

10


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [88]:
array_a = np.random.random(10)
array_b = np.random.random(10)

are_equal = np.array_equal(array_a, array_b)

print(are_equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [89]:
array = np.array([1, 2, 3, 4, 5])

array.flags.writeable = False

try:
    array[0] = 10
except ValueError as e:
    print(e) 

assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [90]:
cartesian = np.random.random((10, 2))

polar = np.column_stack((np.arctan2(cartesian[:, 1], cartesian[:, 0]), np.hypot(cartesian[:, 0], cartesian[:, 1])))

print(polar)

[[0.87174304 0.82336481]
 [1.39585564 0.75638437]
 [0.92298248 1.07807304]
 [0.87867189 0.90310134]
 [0.94559569 0.80567762]
 [0.91118592 0.98772921]
 [0.40814039 0.51291425]
 [0.98897207 0.99917213]
 [0.95859183 0.70247684]
 [0.21259035 0.78812217]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [94]:
vector = np.random.random(10)
print(vector)
vector[vector.argmax()] = 0
print(vector)

[0.64505873 0.94797078 0.668907   0.94937806 0.37788204 0.21564395
 0.10944435 0.02846033 0.64516808 0.87464055]
[0.64505873 0.94797078 0.668907   0.         0.37788204 0.21564395
 0.10944435 0.02846033 0.64516808 0.87464055]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [96]:
x, y = np.meshgrid(np.linspace(0, 1, 10), np.linspace(0, 1, 10))
coordinates = np.stack((x, y), axis=-1)

print(coordinates)

[[[0.         0.        ]
  [0.11111111 0.        ]
  [0.22222222 0.        ]
  [0.33333333 0.        ]
  [0.44444444 0.        ]
  [0.55555556 0.        ]
  [0.66666667 0.        ]
  [0.77777778 0.        ]
  [0.88888889 0.        ]
  [1.         0.        ]]

 [[0.         0.11111111]
  [0.11111111 0.11111111]
  [0.22222222 0.11111111]
  [0.33333333 0.11111111]
  [0.44444444 0.11111111]
  [0.55555556 0.11111111]
  [0.66666667 0.11111111]
  [0.77777778 0.11111111]
  [0.88888889 0.11111111]
  [1.         0.11111111]]

 [[0.         0.22222222]
  [0.11111111 0.22222222]
  [0.22222222 0.22222222]
  [0.33333333 0.22222222]
  [0.44444444 0.22222222]
  [0.55555556 0.22222222]
  [0.66666667 0.22222222]
  [0.77777778 0.22222222]
  [0.88888889 0.22222222]
  [1.         0.22222222]]

 [[0.         0.33333333]
  [0.11111111 0.33333333]
  [0.22222222 0.33333333]
  [0.33333333 0.33333333]
  [0.44444444 0.33333333]
  [0.55555556 0.33333333]
  [0.66666667 0.33333333]
  [0.77777778 0.33333333]
  [0.8

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [99]:
X = np.random.random(10)
Y = np.random.random(10)

C = np.reciprocal(np.subtract.outer(X, Y))

print(C)

[[ 21.39909512   1.13736299   1.80677238  12.82818252 -39.97445236
    1.32876986 -11.17638069   1.26243786   1.52551558   3.32356045]
 [ -2.39705683   2.40779602  11.16520757  -2.59096997  -2.04530269
    3.4642045   -1.80706472   3.04683919   5.21901942  -6.1339509 ]
 [-51.0746118    1.23013844   2.05270103  85.88690627 -10.94976935
    1.45716173  -6.41912175   1.37777475   1.69719947   4.26308343]
 [ -7.00609866   1.44977323   2.7471817   -8.96777572  -4.6624456
    1.77584555  -3.58502426   1.65932565   2.14568172   8.97517753]
 [-46.69537015   1.23292334   2.06046728 101.96779302 -10.73395283
    1.46107103  -6.34434231   1.38126918   1.70250515   4.2967176 ]
 [ -5.93831094   1.50580235   2.95557054  -7.28992431  -4.1641512
    1.86064939  -3.28295739   1.73313471   2.27072964  11.66137993]
 [ -2.66120694   2.18949423   7.63517     -2.90236223  -2.23455561
    3.02961015  -1.95322151   2.70549669   4.29155473  -8.22245682]
 [ -1.27153403  21.71825781  -3.57513877  -1.32410133  -1

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [100]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype}: {info.min} to {info.max}")

for dtype in [np.float16, np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype}: {info.min} to {info.max}")

<class 'numpy.int8'>: -128 to 127
<class 'numpy.int16'>: -32768 to 32767
<class 'numpy.int32'>: -2147483648 to 2147483647
<class 'numpy.int64'>: -9223372036854775808 to 9223372036854775807
<class 'numpy.float16'>: -65504.0 to 65504.0
<class 'numpy.float32'>: -3.4028234663852886e+38 to 3.4028234663852886e+38
<class 'numpy.float64'>: -1.7976931348623157e+308 to 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [110]:
np.set_printoptions(threshold=float("inf"))
array = np.random.random(10)
print(array)

[0.41668277 0.6328222  0.98637688 0.42650006 0.12883737 0.54726256
 0.89733626 0.86690273 0.99596208 0.34464711]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [112]:
arr = np.array([1, 5, 2, 3, 4])

scalar = 3.6
idx = np.abs(arr - scalar).argmin()
closest_value = arr[idx]

print(f"The closest value to {scalar} is {closest_value}")

The closest value to 3.6 is 4


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [117]:
arr = np.array([(1, 2, 255, 0, 0), (3, 4, 0, 255, 0)],
               dtype=[("x", np.int32), ("y", np.int32), ("r", np.uint8), ("g", np.uint8), ("b", np.uint8)])

print(arr)

[(1, 2, 255,   0, 0) (3, 4,   0, 255, 0)]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [115]:
arr = np.random.random((100, 2))

distances = linalg.norm(arr[:, None, :] - arr, axis=-1)

print(distances)

[[0.         0.76040784 0.15167409 0.32781817 1.20421136 0.06276291
  0.90096418 0.94465082 0.58439602 0.2097675  0.71760828 0.17137362
  0.51794429 0.33167065 0.5998516  0.59075257 0.27098088 0.60650173
  0.05575632 0.80350231 0.51106543 0.80145663 1.11883399 0.32523891
  0.68491101 0.11493638 0.85954941 0.85078477 1.02575513 1.09470004
  0.63383082 0.56091378 0.73730998 0.18709807 0.43094633 1.0815737
  0.4339717  0.94592586 0.69635753 0.43997702 0.80635058 0.34326975
  0.85101804 0.61019627 0.87828821 1.13068302 0.82429133 0.57035181
  0.09232111 0.06328697 0.82862204 0.68970868 0.32762044 0.80065747
  0.73001598 0.73949261 0.21719104 0.63273533 0.59931619 0.26709006
  0.67291519 0.16792043 0.98601495 0.39869015 0.52477896 1.0047325
  0.41820208 1.00982362 0.45329097 0.92696268 0.31837691 0.84472624
  0.96157122 0.27289282 0.79345585 0.61670488 0.53455308 0.86554187
  0.95096221 0.56288834 0.33223204 0.61005678 0.3738893  0.94552259
  0.55031939 0.65886328 0.75403565 0.84214754 0.62

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [120]:
arr = np.random.random(10)
arr = arr.astype(np.int32)

print(arr)

[0 0 0 0 0 0 0 0 0 0]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [121]:
arr = np.genfromtxt("file.txt", delimiter=",", dtype=None, missing_values=" ", filling_values=np.nan)

print(arr)

OSError: ignored

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [122]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for i, value in np.ndenumerate(arr):
    print(f"Index: {i}, Value: {value}")

Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (0, 2), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [124]:
size = (5, 5)

center = np.mean(np.indices(size), axis=1)

gaussian = np.empty(size)

for i, j in np.ndindex(size):
    x = i - center[0]
    y = j - center[1]
    distance = np.sqrt(x**2 + y**2)[0]

    gaussian[i, j] = np.exp(-distance**2)

print(gaussian)

[[1.83156389e-02 6.73794700e-03 3.35462628e-04 2.26032941e-06
  2.06115362e-09]
 [3.67879441e-01 1.35335283e-01 6.73794700e-03 4.53999298e-05
  4.13993772e-08]
 [1.00000000e+00 3.67879441e-01 1.83156389e-02 1.23409804e-04
  1.12535175e-07]
 [3.67879441e-01 1.35335283e-01 6.73794700e-03 4.53999298e-05
  4.13993772e-08]
 [1.83156389e-02 6.73794700e-03 3.35462628e-04 2.26032941e-06
  2.06115362e-09]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [135]:
n, m = 5, 5
p = 4

array = np.zeros(n*m)
indices = np.random.choice(n*m, size=p, replace=False)

np.put(array, indices, 1)

array = array.reshape((n, m))

print(array)

[[1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [139]:
A = np.random.random((3, 4))
print(A)
B = A - A.mean(axis=1, keepdims=True)
print(B)

[[0.4280086  0.48170986 0.58699808 0.04850533]
 [0.93997624 0.05255348 0.80990431 0.80704341]
 [0.27900398 0.84091894 0.28635932 0.24155707]]
[[ 0.04170313  0.09540439  0.20069262 -0.33780014]
 [ 0.28760688 -0.59981588  0.15753495  0.15467405]
 [-0.13295585  0.42895911 -0.12560051 -0.17040276]]


#### 59. How to sort an array by the nth column? (★★☆)

In [140]:
A = np.random.randint(0, 10, (5, 3))

indices = A[:, 1].argsort()
A = A[indices]

print(A)

[[7 0 4]
 [5 1 5]
 [7 1 2]
 [4 2 6]
 [1 4 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [143]:
A = np.random.randint(0, 2, (4, 3))
print(A)
has_null_columns = ~A.all(axis=0)

print(has_null_columns)

[[0 1 1]
 [0 1 0]
 [1 1 1]
 [1 1 0]]
[ True False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [144]:
arr = np.random.randint(0, 10, (5,))

val = 3

idx = (np.abs(arr - val)).argmin()

print(arr[idx])

4
2


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [12]:
a = np.arange(3).reshape(3, 1)
b = np.arange(3).reshape(1, 3)
it = np.nditer([a, b, None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [13]:
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name=None):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', None)

a = NamedArray(np.arange(10), name='my_array')
print(a.name)

my_array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [29]:
vec1 = np.array([1, 2, 3, 4, 5])
vec2 = np.array([0, 1, 2, 0, 2])

np.add.at(vec1, vec2, 1)

print(vec1) 

[3 3 5 4 5]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [19]:
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 2, 3, 1, 2])
F = np.zeros(5)

np.add.at(F, I, X)

print(F)

[1. 4. 7. 3. 0.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [30]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [40]:
arr = np.random.randint(0,10,(3,4,3,4))
result = arr.sum(axis=(-1,-2))
print(result)

[[63 50 43 66]
 [52 43 68 61]
 [38 68 51 58]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [42]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.50384711 0.51063865 0.62965081 0.53293321 0.46716705 0.51720025
 0.66970673 0.47173534 0.42817654 0.57338832]


#### 69. How to get the diagonal of a dot product? (★★★)

In [47]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

dot_product = np.dot(A, B)
diagonal = np.diag(dot_product)

print(diagonal)

[19 50]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [57]:
vec = np.array([1,2,3,4,5])
n = 3
vec_new = np.zeros(len(vec) + (len(vec)-1)*(n))
vec_new[::n+1] = vec
print(vec_new)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [66]:
arr1 = np.random.randint(5, size=(5, 5, 3))
arr2 = np.random.randint(5, size=(5, 5))

result = arr1 * arr2[:, :, np.newaxis]

print(result)

[[[12 16 16]
  [ 8  8  6]
  [ 4  6  4]
  [ 2  1  3]
  [ 1  3  3]]

 [[16  4  4]
  [ 4  0  0]
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [12  8 16]
  [ 3  6  6]
  [ 2  0  1]
  [16  4 16]]

 [[ 0  0  0]
  [12  6  6]
  [ 0  0  0]
  [ 0  0  8]
  [ 0  1  2]]

 [[ 4  4  0]
  [ 6  3  6]
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]]


#### 72. How to swap two rows of an array? (★★★)

In [70]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
row_index1 = 0
row_index2 = 2
arr[[row_index1, row_index2]] = arr[[row_index2, row_index1]]

print(arr) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [75]:
C = np.random.randint(0, 100, (10, 3))
A = np.roll(C.repeat(2, axis=1), -1, axis=1)
A = F.reshape(len(A) * 3, 2)
A = np.sort(A, axis=1)
B = F.view(dtype=[('p0', A.dtype), ('p1', A.dtype)])
B = np.unique(B)

print(B)

[( 4, 67) ( 4, 95) ( 6, 21) ( 6, 52) (16, 19) (16, 34) (17, 39) (17, 50)
 (19, 34) (21, 52) (22, 30) (22, 92) (30, 31) (30, 32) (30, 92) (31, 32)
 (39, 50) (41, 55) (41, 74) (42, 63) (42, 85) (51, 55) (51, 95) (53, 62)
 (53, 73) (55, 74) (55, 95) (62, 73) (63, 85) (67, 95)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [89]:
C = np.bincount([4,5,2,3,2,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[2 2 3 4 4 5 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [92]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
window_size = 3
rolling_avg = np.cumsum(arr, dtype=float)
rolling_avg[window_size:] = rolling_avg[window_size:] - rolling_avg[:-window_size]
rolling_avg[window_size - 1:] = rolling_avg[window_size - 1:] / window_size

print(rolling_avg)

[1. 3. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [93]:
from numpy.lib.stride_tricks import as_strided

Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
window_size = 3
stride = 1
rolling_window_view = as_strided(Z, shape=(len(Z) - window_size + 1, window_size), strides=(Z.itemsize, Z.itemsize))
result = np.copy(rolling_window_view)

print(result)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [95]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.05314201, -0.09362216,  0.86841847,  0.39235807, -0.04373636,
        0.30478524,  0.06149867, -0.79776237,  0.22164359, -0.83724435,
        0.7325827 , -0.95221228, -0.11800622,  0.12043151, -0.19702145,
       -0.97186247,  0.57162133,  0.20851436,  0.26446022, -0.50472197,
        0.45661228, -0.89316508,  0.7652847 ,  0.6267761 , -0.13847744,
       -0.84514903,  0.48405609,  0.31071389,  0.88885976,  0.3081736 ,
        0.02577404,  0.88355135, -0.43150959,  0.26146391, -0.00428391,
       -0.82097333, -0.48808033,  0.69797272,  0.31600135,  0.07032213,
        0.86060243,  0.84737983, -0.80721657,  0.16435538, -0.64150306,
        0.26468597,  0.25461935, -0.18960518, -0.65286918,  0.54383089,
       -0.44496096, -0.90314563, -0.44230715, -0.24003693,  0.88789632,
        0.60484051, -0.84451568,  0.27502998, -0.28993422,  0.08556554,
       -0.37598672,  0.50125404,  0.83477695, -0.83789366, -0.74351955,
        0.84367212, -0.60434212, -0.12269729, -0.16382827,  0.00

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [98]:
P0 = np.array([[0, 0], [0, 1], [1, 0]])
P1 = np.array([[1, 1], [1, 2], [2, 1]])

p = np.array([0.5, 0.5])
distances = np.empty(len(P0))
for i in range(len(P0)):
    distances[i] = abs((P1[i,1] - P0[i,1]) * p[0] - (P1[i,0] - P0[i,0]) * p[1] + P1[i,0] * P0[i,1] - P1[i,1] * P0[i,0]) / np.sqrt((P1[i,1] - P0[i,1])**2 + (P1[i,0] - P0[i,0])**2)
print(distances)

[0.         0.70710678 0.70710678]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [101]:
n_points = 10
n_lines = 5

P = np.random.rand(n_points, 2)
P0 = np.random.rand(n_lines, 2)
P1 = np.random.rand(n_lines, 2)

distances = np.empty((n_points, n_lines))
for j in range(n_points):
    for i in range(n_lines):
        v = P1[i] - P0[i]
        proj_Pj = P[j] - np.dot(v, P[j] - P0[i]) / np.dot(v, v) * v
        distances[j, i] = np.linalg.norm(P[j] - proj_Pj)

print(distances)

[[0.2431367  0.24241846 0.10844872 0.33876639 0.08243966]
 [0.60116407 0.76592018 0.40300618 0.02340055 0.60165952]
 [0.30820534 0.63023535 0.46335538 0.03919998 0.33339878]
 [0.56091458 0.32237136 0.02623826 0.42760376 0.33745746]
 [0.51378125 0.28607922 0.03142085 0.44048614 0.28655976]
 [0.1184052  0.21315457 0.16349643 0.30163721 0.01652425]
 [0.61825796 0.17259329 0.21962869 0.61876436 0.29561777]
 [0.24712399 0.02445296 0.16845334 0.35478003 0.38778727]
 [0.71562618 0.50573329 0.05691806 0.31680919 0.53889453]
 [0.06719659 0.46744232 0.55209261 0.07125809 0.00442873]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [109]:
def extract_subarray(arr, shape, center):
  start_idx = []
  end_idx = []
  for i in range(arr.ndim):
    half_shape = shape[i] // 2
    start_idx.append(center[i] - half_shape)
    end_idx.append(center[i] + half_shape + 1)
    
  subarray = arr[tuple(slice(start, end) for start, end in zip(start_idx, end_idx))]
  
  pad_width = []
  for i in range(arr.ndim):
    if subarray.shape[i] < shape[i]:
      pad_width.append((0, shape[i] - subarray.shape[i]))
    else:
      pad_width.append((0, 0))
  subarray = np.pad(subarray, pad_width, mode='constant', constant_values=0)
  
  return subarray

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
subarray = extract_subarray(arr, (2, 2), (1, 1))
print(subarray)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [112]:
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
n_rows = len(Z) - 3
n_cols = 4
R = np.lib.stride_tricks.as_strided(Z, shape=(n_rows, n_cols), strides=(Z.itemsize, Z.itemsize))

print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [138]:
matrix = np.random.randint(2,size=(10,10))
print(matrix)
rank = np.linalg.matrix_rank(a, tol=1e-10)
print(rank)

[[0 0 0 0 1 0 1 1 1 1]
 [1 1 1 0 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 1 1 1 1]
 [1 0 1 1 0 1 0 1 0 0]
 [1 1 1 1 0 0 1 0 1 1]
 [1 1 0 0 1 0 0 0 0 1]
 [0 1 0 0 1 1 0 0 0 0]
 [1 1 0 0 0 0 0 1 1 0]
 [1 1 0 0 0 1 0 1 0 1]]
5


#### 83. How to find the most frequent value in an array?

In [151]:
arr = np.array([1, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])
unique_values, counts = np.unique(arr, return_counts=True)
max_count = counts.max()
frequent_values = unique_values[counts == max_count]

print(f"The most frequent values are {frequent_values} and they occur {max_count} times")

The most frequent values are [3 4] and they occur 4 times


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [176]:
Z = np.random.randint(0, 5, (10, 10))
print(Z)

n = 3
C = np.stack([Z[i:i+n, j:j+n] for i in range(Z.shape[0] - 2) for j in range(Z.shape[1] - 2)])
print(C)

[[4 3 0 1 4 3 0 3 4 3]
 [1 1 0 0 3 3 1 1 4 4]
 [1 0 2 1 1 4 2 4 2 3]
 [0 3 4 4 1 4 2 2 4 0]
 [3 0 1 0 3 1 2 3 2 0]
 [4 2 3 0 1 2 4 4 1 2]
 [3 1 4 2 3 4 2 3 1 1]
 [0 2 0 0 3 0 2 0 2 1]
 [2 4 0 1 4 2 0 0 4 1]
 [0 1 1 0 3 1 2 2 0 4]]
[[[4 3 0]
  [1 1 0]
  [1 0 2]]

 [[3 0 1]
  [1 0 0]
  [0 2 1]]

 [[0 1 4]
  [0 0 3]
  [2 1 1]]

 [[1 4 3]
  [0 3 3]
  [1 1 4]]

 [[4 3 0]
  [3 3 1]
  [1 4 2]]

 [[3 0 3]
  [3 1 1]
  [4 2 4]]

 [[0 3 4]
  [1 1 4]
  [2 4 2]]

 [[3 4 3]
  [1 4 4]
  [4 2 3]]

 [[1 1 0]
  [1 0 2]
  [0 3 4]]

 [[1 0 0]
  [0 2 1]
  [3 4 4]]

 [[0 0 3]
  [2 1 1]
  [4 4 1]]

 [[0 3 3]
  [1 1 4]
  [4 1 4]]

 [[3 3 1]
  [1 4 2]
  [1 4 2]]

 [[3 1 1]
  [4 2 4]
  [4 2 2]]

 [[1 1 4]
  [2 4 2]
  [2 2 4]]

 [[1 4 4]
  [4 2 3]
  [2 4 0]]

 [[1 0 2]
  [0 3 4]
  [3 0 1]]

 [[0 2 1]
  [3 4 4]
  [0 1 0]]

 [[2 1 1]
  [4 4 1]
  [1 0 3]]

 [[1 1 4]
  [4 1 4]
  [0 3 1]]

 [[1 4 2]
  [1 4 2]
  [3 1 2]]

 [[4 2 4]
  [4 2 2]
  [1 2 3]]

 [[2 4 2]
  [2 2 4]
  [2 3 2]]

 [[4 2 3]
  [2 4 0]
  [3 2 0]]

 

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [177]:
class SymmetricArray(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super().__setitem__((i, j), value)
        super().__setitem__((j, i), value)

Z = SymmetricArray((5, 5))
Z[1, 2] = 10
print(Z[1, 2])
print(Z[2, 1])

10.0
10.0


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [180]:
p = 3
n = 4

matrices = np.random.randint(10, size=(p, n, n))
vectors = np.random.randint(10, size=(p, n, 1))

result = np.zeros((n, 1))

for i in range(p):
    result += np.matmul(matrices[i], vectors[i])

print(result)

[[187.]
 [328.]
 [281.]
 [134.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [185]:
from skimage.util import view_as_blocks
arr = np.ones((16,16))
block_sum = view_as_blocks(arr, block_shape=(4, 4)).sum(axis=(2, 3))

print(block_sum)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [218]:
Z = np.arange(100)
np.random.shuffle(Z)
n = 5
print (Z[np.argpartition(-Z,n)[:n]])

[99 98 97 96 95]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [223]:
import itertools

vectors = [np.array([1, 2, 3]), np.array([4, 5]), np.array([6, 7, 8, 9])]
cartesian_product = np.array(list(itertools.product(*vectors)))
print(cartesian_product)

[[1 4 6]
 [1 4 7]
 [1 4 8]
 [1 4 9]
 [1 5 6]
 [1 5 7]
 [1 5 8]
 [1 5 9]
 [2 4 6]
 [2 4 7]
 [2 4 8]
 [2 4 9]
 [2 5 6]
 [2 5 7]
 [2 5 8]
 [2 5 9]
 [3 4 6]
 [3 4 7]
 [3 4 8]
 [3 4 9]
 [3 5 6]
 [3 5 7]
 [3 5 8]
 [3 5 9]]


#### 91. How to create a record array from a regular array? (★★★)

In [226]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

record_array = np.rec.array(data, dtype=[('a', 'i4'), ('b', 'i4'), ('c', 'i4')])

print(record_array)

[[(1, 0, 2) (0, 3, 0)]
 [(4, 0, 5) (0, 6, 0)]
 [(7, 0, 8) (0, 9, 0)]]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [236]:
Z = np.random.rand(int(5e5))
result = np.power(Z, 3)
print(result)

result = np.einsum('i,i,i->i', Z, Z, Z)[:5]
print(result)

power3 = np.vectorize(lambda x: x**3)
result = power3(Z)
print(result)


[0.15178961 0.03138316 0.05458118 ... 0.19252195 0.42320327 0.00771331]
[1.51789609e-01 3.13831589e-02 5.45811787e-02 3.41766479e-01
 1.09167662e-04]
[0.15178961 0.03138316 0.05458118 ... 0.19252195 0.42320327 0.00771331]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [239]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]])
B = np.array([[1, 2], [3, 4]])

mask = np.isin(A, B).any(axis=1)

print(A[mask])

[[1 2 3]
 [4 5 6]]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [243]:
matrix = np.random.randint(10, size=(10, 3))
mask = (matrix[:,0] != matrix[:,1]) | (matrix[:,0] != matrix[:,2]) | (matrix[:,1] != matrix[:,2])
result = matrix[mask]

print(result)

[[0 8 2]
 [4 3 1]
 [2 7 1]
 [6 3 4]
 [4 4 1]
 [6 0 3]
 [3 0 5]
 [0 9 6]
 [7 5 3]
 [3 4 6]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [248]:
array = np.array([0,1,2,3,15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(array[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [249]:
arr = np.random.randint(10, size=(5, 3))
print(arr)

unique_rows = np.unique(arr, axis=0)
print(unique_rows)

[[9 3 1]
 [5 5 3]
 [1 7 7]
 [5 4 1]
 [5 3 4]]
[[1 7 7]
 [5 3 4]
 [5 4 1]
 [5 5 3]
 [9 3 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [252]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print(np.einsum('i,j->ij', A, B))
print(np.einsum('i,j->ij', A, B))
print(np.einsum('i,i->', A, B))
print(np.einsum('i,i->i', A, B))

[[0.76188675 0.72889394 0.31387337 0.36424707 0.33688777 0.09453138
  0.10379111 0.61062643 0.21077322 0.72171714]
 [0.39831139 0.38106288 0.16409176 0.19042694 0.1761236  0.04942063
  0.05426159 0.3192331  0.11019141 0.37731088]
 [0.19311589 0.18475319 0.07955767 0.09232592 0.08539115 0.02396093
  0.026308   0.15477585 0.05342481 0.18293408]
 [0.18980708 0.18158766 0.07819454 0.09074403 0.08392807 0.02355038
  0.02585724 0.15212395 0.05250944 0.17979972]
 [0.20357335 0.19475779 0.08386581 0.09732548 0.09001518 0.02525844
  0.02773261 0.16315715 0.05631783 0.19284018]
 [0.52795001 0.50508762 0.21749879 0.25240529 0.23344664 0.06550559
  0.07192213 0.42313406 0.14605546 0.50011445]
 [0.60330693 0.57718128 0.24854347 0.28843235 0.26676763 0.07485553
  0.08218793 0.48353008 0.16690268 0.57149826]
 [0.88165076 0.84347169 0.36321237 0.42150452 0.3898445  0.10939114
  0.12010645 0.70661324 0.2439055  0.83516674]
 [0.6245946  0.5975471  0.25731332 0.29860967 0.27618052 0.07749681
  0.08508793

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [262]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.17065304  0.21156853]
